### GET all recipes
GET http://localhost:3000/recipes

### GET recipe by ID
GET http://localhost:3000/recipes/6920d11a1181b3d1266f4165

### POST - Create new recipe
POST http://localhost:3000/recipes HTTP/1.1
content-type: application/json

{
  "name": "New Recipe Example",
  "description": "Testing recipe creation",
  "category": "Dessert",
  "ingredients": ["item1", "item2"],
  "instructions": ["step1", "step2"],
  "prepTime": 10,
  "cookTime": 20
}

### PUT - Update recipe
PUT http://localhost:3000/recipes/6920d79d10e71ccb7925aac1 HTTP/1.1
content-type: application/json

{
  "name": "Updated Recipe",
  "description": "Updated description",
  "category": "Updated Category",
  "ingredients": ["updated ingredient"],
  "instructions": ["updated step"],
  "prepTime": 5,
  "cookTime": 15
}

### DELETE - Remove recipe
DELETE http://localhost:3000/recipes/6920dcda2b962514f247405b
